# Generated by Django 6.0.3 on 2026-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production')], default='admin', max_length=20),
        ),
    ]
