# Generated by Django 6.0.3 on 2026-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='advance_paid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='balance_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='driver_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transport_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vehicle_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
